import { useEffect, useState, useCallback } from 'react';
import { useTranslation } from 'react-i18next';
import {
  Card, Row, Col, Input, Button, Space, Typography, Tag, Table, Spin,
  Popconfirm, Empty, Select, message, Tabs, theme, Modal, InputNumber, Switch, Tooltip, Popover,
} from 'antd';
import {
  FileTextOutlined, ThunderboltOutlined, EyeOutlined,
  CopyOutlined, CheckOutlined, ArrowLeftOutlined,
  DownloadOutlined, SaveOutlined, ShareAltOutlined,
  BookOutlined, DeleteOutlined, LinkOutlined,
  ExportOutlined, PlusOutlined, MinusCircleOutlined,
  EditOutlined, GlobalOutlined, SendOutlined, TeamOutlined,
  BarChartOutlined, CloseCircleOutlined,
  LockOutlined,
} from '@ant-design/icons';
import api from '../lib/api';
import type { GeneratedSurvey, SurveyField, SavedSurvey, SurveyResponse } from '../lib/types';

const { Title, Text, Paragraph } = Typography;

function esc(s: string) {
  return s.replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;').replace(/"/g, '&quot;');
}

function buildFieldHtml(field: SurveyField, i: number): string {
  const req = field.required ? '<span style="color:#ef4444">*</span>' : '';
  const nm = `f_${i}`;
  const lbl = `<div class="field"><label for="${nm}">${esc(field.label)} ${req}</label>`;
  let inp = '';
  switch (field.type) {
    case 'textarea':
      inp = `<textarea id="${nm}" name="${nm}" placeholder="${esc(field.placeholder ?? '')}"${field.required ? ' required' : ''}></textarea>`;
      break;
    case 'select':
      inp = `<select id="${nm}" name="${nm}"${field.required ? ' required' : ''}><option value="">Select…</option>${(field.options ?? []).map((o) => `<option value="${esc(o)}">${esc(o)}</option>`).join('')}</select>`;
      break;
    case 'radio':
      inp = `<div class="opts">${(field.options ?? []).map((o) => `<label><input type="radio" name="${nm}" value="${esc(o)}"${field.required ? ' required' : ''}/> ${esc(o)}</label>`).join('')}</div>`;
      break;
    case 'checkbox':
      inp = `<div class="opts">${(field.options ?? []).map((o) => `<label><input type="checkbox" name="${nm}[]" value="${esc(o)}"/> ${esc(o)}</label>`).join('')}</div>`;
      break;
    case 'rating':
      inp = `<div class="stars">${Array.from({ length: field.max ?? 5 }, (_, k) => `<input type="radio" name="${nm}" id="${nm}_${k + 1}" value="${k + 1}"/><label for="${nm}_${k + 1}">★</label>`).join('')}</div>`;
      break;
    default:
      inp = `<input type="${esc(field.type)}" id="${nm}" name="${nm}" placeholder="${esc(field.placeholder ?? '')}"${field.required ? ' required' : ''}/>`;
  }
  return `${lbl}${inp}</div>`;
}

function generateHtml(survey: GeneratedSurvey): string {
  const fields = survey.fields.map(buildFieldHtml).join('\n');
  return `<!DOCTYPE html>
<html lang="en"><head>
<meta charset="UTF-8"/>
<meta name="viewport" content="width=device-width,initial-scale=1.0"/>
<title>${esc(survey.title)}</title>
<style>
*,*::before,*::after{box-sizing:border-box}
body{font-family:-apple-system,BlinkMacSystemFont,'Segoe UI',sans-serif;max-width:680px;margin:40px auto;padding:0 20px;color:#1e293b;background:#fff;line-height:1.6}
h1{font-size:1.5rem;font-weight:700;margin-bottom:6px}
p.d{color:#64748b;margin-bottom:32px;font-size:.95rem}
.field{margin-bottom:20px}
label{display:block;font-size:.875rem;font-weight:600;color:#374151;margin-bottom:6px}
input,textarea,select{width:100%;padding:8px 12px;border:1px solid #d1d5db;border-radius:6px;font-size:.9rem;color:#1e293b;background:#f9fafb}
input:focus,textarea:focus,select:focus{outline:none;border-color:#2563eb;background:#fff}
textarea{resize:vertical;min-height:80px}
.opts label{font-weight:400;display:flex;align-items:center;gap:8px;margin-bottom:4px}
.stars input[type=radio]{display:none}.stars label{font-size:1.5rem;cursor:pointer;color:#d1d5db;margin:0}
.btn{display:block;width:100%;padding:12px;background:#2563eb;color:#fff;border:none;border-radius:8px;font-size:1rem;font-weight:600;cursor:pointer;margin-top:32px}
.btn:hover{background:#1d4ed8}
footer{margin-top:48px;text-align:center;font-size:.75rem;color:#94a3b8}
@media print{body{margin:0}.btn{display:none}}
</style></head>
<body>
<h1>${esc(survey.title)}</h1>
${survey.description ? `<p class="d">${esc(survey.description)}</p>` : ''}
<form>
${fields}
<button type="submit" class="btn">Submit</button>
</form>
<footer>Generated by ISET Observatory · Survey Generator</footer>
</body></html>`;
}

const PLATFORMS = [
  { name: 'Google Forms', desc: 'Free, unlimited responses, Google account required.', color: '#4285f4', url: 'https://forms.google.com/create' },
  { name: 'Tally.so', desc: 'Free, unlimited responses, no sign-up required to fill.', color: '#2c2c2c', url: 'https://tally.so' },
  { name: 'Typeform', desc: 'Beautiful conversational forms, free tier available.', color: '#262627', url: 'https://www.typeform.com' },
  { name: 'Microsoft Forms', desc: 'Integrated with Microsoft 365, great for institutions.', color: '#0078d4', url: 'https://forms.microsoft.com' },
];

const FIELD_TYPES: { value: SurveyField['type']; label: string }[] = [
  { value: 'text', label: 'Text' },
  { value: 'textarea', label: 'Text Area' },
  { value: 'number', label: 'Number' },
  { value: 'email', label: 'Email' },
  { value: 'date', label: 'Date' },
  { value: 'select', label: 'Select' },
  { value: 'radio', label: 'Radio' },
  { value: 'checkbox', label: 'Checkbox' },
  { value: 'rating', label: 'Rating' },
];

const CLIENT_TYPE_OPTIONS = [
  { value: 'student', label: 'Student' },
  { value: 'alumni', label: 'Alumni' },
  { value: 'teacher', label: 'Teacher' },
];

const LANGUAGE_OPTIONS = [
  { value: 'en', label: 'English' },
  { value: 'fr', label: 'French' },
  { value: 'ar', label: 'Arabic' },
];

const AUDIENCE_OPTIONS = [
  { value: 'students', label: 'Students' },
  { value: 'alumni', label: 'Alumni' },
  { value: 'teachers', label: 'Teachers' },
  { value: 'staff', label: 'Staff' },
  { value: 'general', label: 'General / Mixed' },
];

function SurveyFieldPreview({ field }: { field: SurveyField }) {
  const { token } = theme.useToken();

  return (
    <div>
      <label style={{ display: 'block', fontSize: 14, fontWeight: 500, marginBottom: 6, color: token.colorTextSecondary }}>
        {field.label}
        {field.required && <Text type="danger"> *</Text>}
      </label>
      {(field.type === 'text' || field.type === 'email' || field.type === 'date') && (
        <Input type={field.type} placeholder={field.placeholder} disabled />
      )}
      {field.type === 'number' && (
        <Input type="number" placeholder={field.placeholder} disabled />
      )}
      {field.type === 'textarea' && (
        <Input.TextArea placeholder={field.placeholder} rows={3} disabled />
      )}
      {field.type === 'select' && (
        <Select disabled style={{ width: '100%' }} placeholder="Select…" options={field.options?.map((o) => ({ value: o, label: o }))} />
      )}
      {field.type === 'radio' && (
        <div style={{ display: 'flex', flexDirection: 'column', gap: 4 }}>
          {field.options?.map((o) => (
            <label key={o} style={{ display: 'flex', alignItems: 'center', gap: 8 }}>
              <input type="radio" disabled /> <Text type="secondary">{o}</Text>
            </label>
          ))}
        </div>
      )}
      {field.type === 'checkbox' && (
        <div style={{ display: 'flex', flexDirection: 'column', gap: 4 }}>
          {field.options?.map((o) => (
            <label key={o} style={{ display: 'flex', alignItems: 'center', gap: 8 }}>
              <input type="checkbox" disabled /> <Text type="secondary">{o}</Text>
            </label>
          ))}
        </div>
      )}
      {field.type === 'rating' && (
        <Space>
          {Array.from({ length: field.max || 5 }, (_, i) => (
            <span key={i} style={{ fontSize: 24, color: i < 3 ? token.colorWarning : token.colorBorder }}>★</span>
          ))}
        </Space>
      )}
    </div>
  );
}

export default function SurveyGeneratorPage() {
  const { t } = useTranslation();
  const { token } = theme.useToken();
  const [goal, setGoal] = useState('');
  const [context, setContext] = useState('');
  const [numFields, setNumFields] = useState<number | null>(null);
  const [language, setLanguage] = useState<string | undefined>(undefined);
  const [audience, setAudience] = useState<string | undefined>(undefined);
  const [generating, setGenerating] = useState(false);
  const [survey, setSurvey] = useState<GeneratedSurvey | null>(null);
  const [copied, setCopied] = useState(false);
  const [previewMode, setPreviewMode] = useState(false);

  const [saved, setSaved] = useState<SavedSurvey[]>([]);
  const [loadingSaved, setLoadingSaved] = useState(true);
  const [saving, setSaving] = useState(false);
  const [savedId, setSavedId] = useState<number | null>(null);
  const [editingSavedId, setEditingSavedId] = useState<number | null>(null);

  const [shareOpen, setShareOpen] = useState(false);
  const [shareUrl, setShareUrl] = useState('');
  const [copiedEmbed, setCopiedEmbed] = useState(false);
  const [copiedLink, setCopiedLink] = useState(false);

  const [editingFields, setEditingFields] = useState(false);

  const [publishModalOpen, setPublishModalOpen] = useState(false);
  const [publishIsPublic, setPublishIsPublic] = useState(true);
  const [publishClientTypes, setPublishClientTypes] = useState<string[]>([]);

  const [responsesModalOpen, setResponsesModalOpen] = useState(false);
  const [responses, setResponses] = useState<SurveyResponse[]>([]);
  const [responsesLoading, setResponsesLoading] = useState(false);
  const [_responsesSurveyId, setResponsesSurveyId] = useState<number | null>(null);

  const fetchSaved = useCallback(async () => {
    setLoadingSaved(true);
    try {
      const { data } = await api.get<{ success: boolean; data: SavedSurvey[] }>('/surveys');
      if (data.success) setSaved(data.data);
    } catch {
      message.error(t('surveys.fetchFailed'));
    }
    finally { setLoadingSaved(false); }
  }, []);

  useEffect(() => { fetchSaved(); }, [fetchSaved]);

  async function handleGenerate(e: React.FormEvent) {
    e.preventDefault();
    if (!goal.trim() || generating) return;
    setGenerating(true);
    setSurvey(null);
    setPreviewMode(false);
    setSavedId(null);
    setEditingSavedId(null);
    setShareOpen(false);
    setEditingFields(false);
    try {
      const res = await api.post('/ai/survey/generate', {
        goal: goal.trim(),
        context: context.trim() || undefined,
        numFields: numFields || undefined,
        language: language || undefined,
        audience: audience || undefined,
      });
      setSurvey(res.data.data);
    } catch (err: unknown) {
      const msg = (err as { response?: { data?: { message?: string } } })?.response?.data?.message;
      message.error(msg || t('surveys.generateFailed'));
    } finally {
      setGenerating(false);
    }
  }

  async function handleSaveDraft() {
    if (!survey || saving) return;
    setSaving(true);
    try {
      const payload: any = {
        title: survey.title,
        description: survey.description,
        goal: survey.goal,
        schema: survey,
        isPublic: false,
        clientTypes: [],
      };
      if (editingSavedId) {
        await api.put(`/surveys/${editingSavedId}`, { ...payload, status: 'draft' });
        message.success(t('surveys.updateSuccess'));
        setSavedId(editingSavedId);
      } else {
        const { data } = await api.post<{ success: boolean; data: SavedSurvey }>('/surveys', payload);
        setSavedId(data.data.id);
        setEditingSavedId(data.data.id);
        message.success(t('surveys.saveSuccess'));
      }
      await fetchSaved();
    } catch {
      message.error(t('surveys.saveFailed'));
    } finally {
      setSaving(false);
    }
  }

  function openPublishModal() {
    setPublishIsPublic(true);
    setPublishClientTypes([]);
    setPublishModalOpen(true);
  }

  async function handlePublish() {
    if (!survey) return;
    setSaving(true);
    try {
      const payload: any = {
        title: survey.title,
        description: survey.description,
        goal: survey.goal,
        schema: survey,
        isPublic: publishIsPublic,
        clientTypes: publishClientTypes,
        status: 'published',
      };
      if (editingSavedId) {
        await api.put(`/surveys/${editingSavedId}`, payload);
        message.success(t('surveys.publishSuccess'));
        setSavedId(editingSavedId);
      } else {
        const { data } = await api.post<{ success: boolean; data: SavedSurvey }>('/surveys', payload);
        setSavedId(data.data.id);
        setEditingSavedId(data.data.id);
        message.success(t('surveys.publishSuccess'));
      }
      setPublishModalOpen(false);
      await fetchSaved();
    } catch {
      message.error(t('surveys.publishFailed'));
    } finally {
      setSaving(false);
    }
  }

  async function handleUnpublish(id: number) {
    try {
      await api.put(`/surveys/${id}`, { status: 'draft', isPublic: false, clientTypes: [] });
      message.success(t('surveys.unpublishSuccess'));
      await fetchSaved();
      if (editingSavedId === id) {
        setSavedId(id);
      }
    } catch {
      message.error(t('surveys.publishFailed'));
    }
  }

  function handleDownloadHtml() {
    if (!survey) return;
    const html = generateHtml(survey);
    const blob = new Blob([html], { type: 'text/html' });
    const a = document.createElement('a');
    a.href = URL.createObjectURL(blob);
    a.download = `${survey.title.replace(/[^a-z0-9]/gi, '_').toLowerCase()}.html`;
    a.click();
    URL.revokeObjectURL(a.href);
    message.success('HTML downloaded.');
  }

  async function copyJSON() {
    if (!survey) return;
    await navigator.clipboard.writeText(JSON.stringify(survey, null, 2));
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
    message.success('JSON copied to clipboard.');
  }

  async function copyEmbed() {
    const url = shareUrl.trim() || 'YOUR_SURVEY_URL';
    const snippet = `<iframe src="${url}" width="100%" height="600" style="border:none; border-radius:8px;" title="${survey?.title ?? 'Survey'}"></iframe>`;
    await navigator.clipboard.writeText(snippet);
    setCopiedEmbed(true);
    setTimeout(() => setCopiedEmbed(false), 2000);
  }

  async function copyLink() {
    await navigator.clipboard.writeText(shareUrl.trim());
    setCopiedLink(true);
    setTimeout(() => setCopiedLink(false), 2000);
  }

  async function downloadQrPng() {
    const url = shareUrl.trim();
    if (!url) return;
    const apiUrl = `https://api.qrserver.com/v1/create-qr-code/?size=200x200&data=${encodeURIComponent(url)}`;
    const res = await fetch(apiUrl);
    const blob = await res.blob();
    const objUrl = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = objUrl;
    a.download = `${survey?.title?.replace(/[^a-z0-9]/gi, '_').toLowerCase() ?? 'survey'}_qr.png`;
    a.click();
    URL.revokeObjectURL(objUrl);
  }

  async function loadSavedSurvey(s: SavedSurvey) {
    setGoal(s.goal ?? '');
    setSavedId(s.id);
    setEditingSavedId(s.id);
    setPreviewMode(false);
    setShareOpen(false);
    setEditingFields(false);
    if (s.schema) {
      setSurvey(s.schema);
    } else {
      try {
        const res = await api.get(`/surveys/${s.id}`);
        if (res.data.success && res.data.data.schema) {
          setSurvey(res.data.data.schema);
        } else {
          message.info(t('surveys.noSchemaAvailable'));
          setSurvey(null);
        }
      } catch {
        message.error(t('surveys.fetchFailed'));
      }
    }
  }

  async function deleteSaved(id: number) {
    try {
      await api.delete(`/surveys/${id}`);
      setSaved((prev) => prev.filter((s) => s.id !== id));
      if (savedId === id) { setSavedId(null); setEditingSavedId(null); setSurvey(null); }
      message.success(t('surveys.deleteSuccess'));
    } catch {
      message.error(t('surveys.deleteFailed'));
    }
  }

  async function viewResponses(surveyId: number) {
    setResponsesSurveyId(surveyId);
    setResponsesModalOpen(true);
    setResponsesLoading(true);
    try {
      const res = await api.get(`/surveys/${surveyId}/responses`);
      setResponses(res.data.data || []);
    } catch {
      message.error(t('surveys.responsesFetchFailed'));
    } finally {
      setResponsesLoading(false);
    }
  }

  function addField() {
    if (!survey) return;
    const newField: SurveyField = {
      id: `f_${Date.now()}`,
      type: 'text',
      label: 'New Field',
      placeholder: '',
      required: false,
    };
    setSurvey({ ...survey, fields: [...survey.fields, newField] });
  }

  function removeField(fieldId: string) {
    if (!survey) return;
    setSurvey({ ...survey, fields: survey.fields.filter((f) => f.id !== fieldId) });
  }

  function updateField(fieldId: string, updates: Partial<SurveyField>) {
    if (!survey) return;
    setSurvey({
      ...survey,
      fields: survey.fields.map((f) => f.id === fieldId ? { ...f, ...updates } : f),
    });
  }

  function moveField(fieldId: string, direction: 'up' | 'down') {
    if (!survey) return;
    const idx = survey.fields.findIndex((f) => f.id === fieldId);
    if (idx < 0) return;
    if (direction === 'up' && idx === 0) return;
    if (direction === 'down' && idx === survey.fields.length - 1) return;
    const newFields = [...survey.fields];
    const swapIdx = direction === 'up' ? idx - 1 : idx + 1;
    [newFields[idx], newFields[swapIdx]] = [newFields[swapIdx], newFields[idx]];
    setSurvey({ ...survey, fields: newFields });
  }

  const statusColor = (status: string) => {
    switch (status) {
      case 'published': return 'green';
      case 'closed': return 'red';
      default: return 'default';
    }
  };

  if (previewMode && survey) {
    return (
      <div style={{ maxWidth: 640, margin: '0 auto', display: 'flex', flexDirection: 'column', gap: 24 }}>
        <Button
          type="link"
          icon={<ArrowLeftOutlined />}
          onClick={() => setPreviewMode(false)}
        >
          Back to editor
        </Button>
        <Card>
          <Title level={4}>{survey.title}</Title>
          <Paragraph type="secondary">{survey.description}</Paragraph>
          <div style={{ display: 'flex', flexDirection: 'column', gap: 20 }}>
            {survey.fields.map((field) => <SurveyFieldPreview key={field.id} field={field} />)}
          </div>
          <Button type="primary" block disabled style={{ marginTop: 24, opacity: 0.5 }}>
            Submit (Preview Only)
          </Button>
        </Card>
      </div>
    );
  }

  const tabItems = [
    {
      key: 'generate',
      label: <span><ThunderboltOutlined /> {t('surveys.generate')}</span>,
      children: (
        <Row gutter={[24, 24]}>
          <Col xs={24} lg={14}>
            <Card>
              <div style={{ marginBottom: 16 }}>
                <Text strong style={{ display: 'block', marginBottom: 4, fontSize: 14 }}>
                  {t('surveys.howToUse')}
                </Text>
                <Text type="secondary" style={{ fontSize: 13 }}>
                  {t('surveys.howToUseDesc')}
                </Text>
              </div>
              <form onSubmit={handleGenerate} style={{ display: 'flex', flexDirection: 'column', gap: 16 }}>
                <div>
                  <Text strong style={{ display: 'block', marginBottom: 4 }}>
                    {t('surveys.goal')} <Text type="danger">*</Text>
                  </Text>
                  <Input.TextArea
                    value={goal}
                    onChange={(e) => setGoal(e.target.value)}
                    rows={3}
                    placeholder={t('surveys.goalPlaceholder')}
                  />
                </div>
                <div>
                  <Text strong style={{ display: 'block', marginBottom: 4 }}>
                    {t('surveys.context')}
                  </Text>
                  <Input
                    value={context}
                    onChange={(e) => setContext(e.target.value)}
                    placeholder={t('surveys.contextPlaceholder')}
                  />
                </div>
                <Row gutter={12}>
                  <Col span={8}>
                    <Text strong style={{ display: 'block', marginBottom: 4 }}>{t('surveys.numFields')}</Text>
                    <InputNumber
                      min={1}
                      max={30}
                      value={numFields}
                      onChange={(v) => setNumFields(v)}
                      placeholder="5-15"
                      style={{ width: '100%' }}
                    />
                  </Col>
                  <Col span={8}>
                    <Text strong style={{ display: 'block', marginBottom: 4 }}>{t('surveys.language')}</Text>
                    <Select
                      allowClear
                      style={{ width: '100%' }}
                      value={language}
                      onChange={(v) => setLanguage(v)}
                      placeholder={t('surveys.languagePlaceholder')}
                      options={LANGUAGE_OPTIONS}
                    />
                  </Col>
                  <Col span={8}>
                    <Text strong style={{ display: 'block', marginBottom: 4 }}>{t('surveys.audience')}</Text>
                    <Select
                      allowClear
                      style={{ width: '100%' }}
                      value={audience}
                      onChange={(v) => setAudience(v)}
                      placeholder={t('surveys.audiencePlaceholder')}
                      options={AUDIENCE_OPTIONS}
                    />
                  </Col>
                </Row>
                <Button
                  type="primary"
                  htmlType="submit"
                  icon={<ThunderboltOutlined />}
                  loading={generating}
                  disabled={generating || !goal.trim()}
                  size="large"
                  block
                >
                  {generating ? t('surveys.generating') : t('surveys.generate')}
                </Button>
              </form>
            </Card>
          </Col>

          <Col xs={24} lg={10}>
            <Card
              title={<Space><BookOutlined style={{ color: token.colorPrimary }} /> {t('surveys.savedSurveys')}</Space>}
              styles={{ body: { padding: loadingSaved ? 24 : 0 } }}
            >
              {loadingSaved ? (
                <Spin style={{ display: 'block', margin: '16px auto' }} />
              ) : saved.length === 0 ? (
                <Empty description={t('surveys.noSaved')} image={Empty.PRESENTED_IMAGE_SIMPLE} style={{ padding: 24 }} />
              ) : (
                <div style={{ maxHeight: 500, overflowY: 'auto' }}>
                  {saved.map((s) => (
                    <div
                      key={s.id}
                      style={{
                        padding: '10px 16px',
                        cursor: 'pointer',
                        backgroundColor: savedId === s.id ? token.colorPrimaryBg : 'transparent',
                        borderLeft: savedId === s.id ? `3px solid ${token.colorPrimary}` : '3px solid transparent',
                        transition: 'all 0.2s',
                      }}
                      onClick={() => loadSavedSurvey(s)}
                    >
                      <div style={{ display: 'flex', alignItems: 'center', gap: 8 }}>
                        <div style={{ flex: 1, minWidth: 0 }}>
                          <div style={{ display: 'flex', alignItems: 'center', gap: 6 }}>
                            <Text strong ellipsis style={{ display: 'block', fontSize: 13 }}>{s.title}</Text>
                            <Tag color={statusColor(s.status)} style={{ fontSize: 10, margin: 0 }}>
                              {s.status}
                            </Tag>
                          </div>
                          <Text type="secondary" style={{ fontSize: 11 }}>{s.goal?.slice(0, 50)}{s.goal && s.goal.length > 50 ? '…' : ''}</Text>
                          <br />
                          <Space size={8} style={{ fontSize: 10, marginTop: 2 }}>
                            <Text type="secondary">{new Date(s.created_at).toLocaleDateString()}</Text>
                            {s.responses_count > 0 && (
                              <Text type="secondary"><BarChartOutlined /> {s.responses_count}</Text>
                            )}
                            {s.is_public && <Tag color="green" icon={<GlobalOutlined />} style={{ fontSize: 9, margin: 0 }}>Public</Tag>}
                            {(s.client_types ?? []).length > 0 && (
                              <Tag color="blue" icon={<TeamOutlined />} style={{ fontSize: 9, margin: 0 }}>
                                {(s.client_types ?? []).join(', ')}
                              </Tag>
                            )}
                          </Space>
                        </div>
                        <Space size={2}>
                          {s.status === 'published' && (
                            <Tooltip title={t('surveys.unpublish')}>
                              <Button
                                type="text" size="small"
                                icon={<CloseCircleOutlined />}
                                onClick={(e) => { e.stopPropagation(); handleUnpublish(s.id); }}
                              />
                            </Tooltip>
                          )}
                          {s.responses_count > 0 && (
                            <Tooltip title={t('surveys.viewResponses')}>
                              <Button
                                type="text" size="small"
                                icon={<BarChartOutlined />}
                                onClick={(e) => { e.stopPropagation(); viewResponses(s.id); }}
                              />
                            </Tooltip>
                          )}
                          <Popconfirm title={t('surveys.deleteConfirm')} onConfirm={() => deleteSaved(s.id)} okButtonProps={{ danger: true }}>
                            <Button type="text" size="small" danger icon={<DeleteOutlined />} onClick={(e) => e.stopPropagation()} />
                          </Popconfirm>
                        </Space>
                      </div>
                    </div>
                  ))}
                </div>
              )}
            </Card>
          </Col>
        </Row>
      ),
    },
    ...(survey
      ? [
        {
          key: 'result',
          label: <span><FileTextOutlined /> Result</span>,
          children: (
            <div style={{ display: 'flex', flexDirection: 'column', gap: 16 }}>
              <Card>
                <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'flex-start', flexWrap: 'wrap', gap: 12 }}>
                  <div>
                    <Title level={4} style={{ margin: 0 }}>{survey.title}</Title>
                    <Paragraph type="secondary" style={{ margin: '4px 0 0' }}>{survey.description}</Paragraph>
                    <Text type="secondary" style={{ fontSize: 12, marginTop: 8, display: 'block' }}>
                      {survey.fields.length} {t('surveys.fields')}
                      {savedId && <Tag color="success" style={{ marginLeft: 8 }}>{t('surveys.saved')}</Tag>}
                      {editingSavedId && saved[findIndex(saved, editingSavedId)]?.status === 'published' && (
                        <Tag color="green" style={{ marginLeft: 8 }} icon={<GlobalOutlined />}>{t('surveys.published')}</Tag>
                      )}
                    </Text>
                  </div>
                  <Space wrap>
                    <Button icon={<EyeOutlined />} onClick={() => setPreviewMode(true)}>{t('surveys.preview')}</Button>
                    <Button icon={copied ? <CheckOutlined /> : <CopyOutlined />} onClick={copyJSON}>
                      {copied ? 'Copied!' : 'Copy JSON'}
                    </Button>
                    <Button icon={<DownloadOutlined />} onClick={handleDownloadHtml}>{t('surveys.exportHTML')}</Button>
                    <Button icon={<SaveOutlined />} onClick={handleSaveDraft} loading={saving}>
                      {saving ? t('common.loading') : editingSavedId ? t('surveys.updateDraft') : t('surveys.saveDraft')}
                    </Button>
                    <Button type="primary" icon={<SendOutlined />} onClick={openPublishModal}>
                      {t('surveys.publish')}
                    </Button>
                    <Button icon={<ShareAltOutlined />} onClick={() => setShareOpen((v) => !v)}>{t('surveys.share')}</Button>
                  </Space>
                </div>
              </Card>

              {shareOpen && (
                <Card>
                  <Title level={5} style={{ display: 'flex', alignItems: 'center', gap: 8 }}>
                    <ShareAltOutlined style={{ color: token.colorPrimary }} /> {t('surveys.shareLink')}
                  </Title>

                  <div style={{ marginBottom: 16 }}>
                    <Text strong style={{ display: 'block', marginBottom: 4, fontSize: 12 }}>
                      Paste your hosted survey URL to generate a QR code
                    </Text>
                    <Space.Compact style={{ width: '100%' }}>
                      <Input
                        prefix={<LinkOutlined />}
                        value={shareUrl}
                        onChange={(e) => setShareUrl(e.target.value)}
                        placeholder="https://your-domain.com/survey.html"
                      />
                      {shareUrl.trim() && (
                        <Button icon={copiedLink ? <CheckOutlined /> : <CopyOutlined />} onClick={copyLink}>
                          {copiedLink ? 'Copied!' : t('surveys.copyLink')}
                        </Button>
                      )}
                    </Space.Compact>
                    <Text type="secondary" style={{ fontSize: 11, marginTop: 4, display: 'block' }}>
                      First, export the HTML file, host it (e.g. GitHub Pages, Netlify), then paste the public URL here.
                    </Text>
                  </div>

                  <Row gutter={24}>
                    <Col style={{ display: 'flex', flexDirection: 'column', alignItems: 'center', gap: 8 }}>
                      <div style={{ borderRadius: 12, padding: 12, backgroundColor: '#fff', border: `1px solid ${token.colorBorder}`, opacity: shareUrl.trim() ? 1 : 0.2 }}>
                        <img
                          src={`https://api.qrserver.com/v1/create-qr-code/?size=200x200&data=${encodeURIComponent(shareUrl.trim() || 'https://example.com')}`}
                          alt="QR code"
                          width={200}
                          height={200}
                        />
                      </div>
                      {shareUrl.trim() ? (
                        <Button size="small" icon={<DownloadOutlined />} onClick={downloadQrPng}>Download QR PNG</Button>
                      ) : (
                        <Text type="secondary" style={{ fontSize: 12 }}>Enter URL to generate QR</Text>
                      )}
                    </Col>
                    <Col flex="auto" style={{ display: 'flex', flexDirection: 'column', gap: 8 }}>
                      <Text strong style={{ fontSize: 12 }}>Embed snippet — paste into your LMS or website:</Text>
                      <pre style={{
                        fontSize: 12, padding: 12, borderRadius: 8,
                        backgroundColor: token.colorBgContainer, overflowX: 'auto',
                        border: `1px solid ${token.colorBorder}`,
                      }}>
                        {`<iframe\n  src="${shareUrl.trim() || 'YOUR_SURVEY_URL'}"\n  width="100%" height="600"\n  style="border:none; border-radius:8px;"\n  title="${survey.title}"\n></iframe>`}
                      </pre>
                      <Button size="small" icon={copiedEmbed ? <CheckOutlined /> : <CopyOutlined />} onClick={copyEmbed}>
                        {copiedEmbed ? 'Copied!' : 'Copy snippet'}
                      </Button>
                    </Col>
                  </Row>
                </Card>
              )}

              <Card
                title={
                  <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center' }}>
                    <Space><EditOutlined style={{ color: token.colorPrimary }} /> {t('surveys.editFields')}</Space>
                    <Space>
                      <Button
                        size="small"
                        type={editingFields ? 'primary' : 'default'}
                        icon={<EditOutlined />}
                        onClick={() => setEditingFields((v) => !v)}
                      >
                        {editingFields ? t('common.close') : t('surveys.editFields')}
                      </Button>
                      {editingFields && (
                        <Button size="small" icon={<PlusOutlined />} onClick={addField}>{t('surveys.addField')}</Button>
                      )}
                    </Space>
                  </div>
                }
                size="small"
              >
                {editingFields ? (
                  <div style={{ display: 'flex', flexDirection: 'column', gap: 8 }}>
                    {survey.fields.map((field, idx) => (
                      <Card
                        key={field.id}
                        size="small"
                        style={{ backgroundColor: token.colorBgContainer }}
                      >
                        <Row gutter={[12, 8]} align="middle">
                          <Col flex="none">
                            <Space direction="vertical" size={2}>
                              <Button
                                type="text"
                                size="small"
                                icon={<span style={{ fontSize: 10 }}>▲</span>}
                                disabled={idx === 0}
                                onClick={() => moveField(field.id, 'up')}
                              />
                              <Button
                                type="text"
                                size="small"
                                icon={<span style={{ fontSize: 10 }}>▼</span>}
                                disabled={idx === survey.fields.length - 1}
                                onClick={() => moveField(field.id, 'down')}
                              />
                            </Space>
                          </Col>
                          <Col xs={24} sm={8} md={6}>
                            <Text type="secondary" style={{ fontSize: 11, display: 'block', marginBottom: 2 }}>{t('surveys.fieldName')}</Text>
                            <Input
                              size="small"
                              value={field.label}
                              onChange={(e) => updateField(field.id, { label: e.target.value })}
                            />
                          </Col>
                          <Col xs={12} sm={6} md={4}>
                            <Text type="secondary" style={{ fontSize: 11, display: 'block', marginBottom: 2 }}>{t('surveys.fieldType')}</Text>
                            <Select
                              size="small"
                              style={{ width: '100%' }}
                              value={field.type}
                              onChange={(v) => updateField(field.id, { type: v as SurveyField['type'] })}
                              options={FIELD_TYPES}
                            />
                          </Col>
                          <Col xs={12} sm={6} md={4}>
                            <Text type="secondary" style={{ fontSize: 11, display: 'block', marginBottom: 2 }}>Placeholder</Text>
                            <Input
                              size="small"
                              value={field.placeholder ?? ''}
                              onChange={(e) => updateField(field.id, { placeholder: e.target.value })}
                            />
                          </Col>
                          <Col xs={12} sm={4} md={3}>
                            <Text type="secondary" style={{ fontSize: 11, display: 'block', marginBottom: 2 }}>{t('surveys.fieldRequired')}</Text>
                            <Select
                              size="small"
                              style={{ width: '100%' }}
                              value={field.required ? 'yes' : 'no'}
                              onChange={(v) => updateField(field.id, { required: v === 'yes' })}
                              options={[{ value: 'yes', label: 'Yes' }, { value: 'no', label: 'No' }]}
                            />
                          </Col>
                          <Col xs={24} sm={12} md={5}>
                            <Text type="secondary" style={{ fontSize: 11, display: 'block', marginBottom: 2 }}>
                              {t('surveys.fieldOptions')} <Text type="secondary">(comma-sep)</Text>
                            </Text>
                            <Input
                              size="small"
                              value={(field.options ?? []).join(', ')}
                              onChange={(e) => {
                                const opts = e.target.value.split(',').map((o) => o.trim()).filter(Boolean);
                                updateField(field.id, { options: opts.length ? opts : undefined });
                              }}
                              disabled={!['select', 'radio', 'checkbox'].includes(field.type)}
                            />
                          </Col>
                          <Col flex="none">
                            <Button
                              type="text"
                              danger
                              size="small"
                              icon={<MinusCircleOutlined />}
                              onClick={() => removeField(field.id)}
                              style={{ marginTop: 18 }}
                            />
                          </Col>
                        </Row>
                      </Card>
                    ))}
                  </div>
                ) : (
                  <Table
                    dataSource={survey.fields.map((f, i) => ({ key: f.id, ...f, idx: i }))}
                    pagination={false}
                    size="small"
                    columns={[
                      { title: '#', dataIndex: 'idx', width: 40, render: (i: number) => i + 1 },
                      { title: t('surveys.fieldName'), dataIndex: 'label', ellipsis: true },
                      { title: t('surveys.fieldType'), dataIndex: 'type', width: 100, render: (v: string) => <Tag>{v}</Tag> },
                      { title: t('surveys.fieldRequired'), dataIndex: 'required', width: 80, render: (v: boolean) => v ? <Tag color="red">Yes</Tag> : <Tag>No</Tag> },
                      { title: t('surveys.fieldOptions'), dataIndex: 'options', render: (v: string[] | undefined) => v?.join(', ') || '—' },
                    ]}
                  />
                )}
              </Card>

              <Card title={<Space><ExportOutlined style={{ color: token.colorPrimary }} /> {t('surveys.externalPlatforms')}</Space>}>
                <Paragraph type="secondary" style={{ fontSize: 12 }}>
                  {t('surveys.externalPlatformsDesc')}
                </Paragraph>
                <Row gutter={[12, 12]}>
                  {PLATFORMS.map((p) => (
                    <Col xs={12} md={6} key={p.name}>
                      <a href={p.url} target="_blank" rel="noopener noreferrer" style={{ textDecoration: 'none' }}>
                        <Card hoverable size="small" style={{ textAlign: 'center' }}>
                          <Space direction="vertical" size={4}>
                            <Text strong style={{ color: p.color }}>{p.name}</Text>
                            <Text type="secondary" style={{ fontSize: 11 }}>{p.desc}</Text>
                          </Space>
                        </Card>
                      </a>
                    </Col>
                  ))}
                </Row>
              </Card>

              <Card title="JSON Schema" size="small">
                <pre style={{
                  padding: 16, fontSize: 12, overflowX: 'auto', maxHeight: 256,
                  backgroundColor: token.colorBgContainer, color: token.colorSuccess,
                  borderRadius: 8,
                }}>
                  {JSON.stringify(survey, null, 2)}
                </pre>
              </Card>
            </div>
          ),
        },
      ]
      : []),
  ];

  return (
    <div style={{ display: 'flex', flexDirection: 'column', gap: 20 }}>
      <div>
        <Title level={3} style={{ display: 'flex', alignItems: 'center', gap: 8, margin: 0 }}>
          <FileTextOutlined style={{ color: token.colorPrimary }} /> {t('surveys.pageTitle')}
        </Title>
        <Text type="secondary">{t('surveys.subtitle')}</Text>
      </div>

      <Tabs items={tabItems} defaultActiveKey="generate" />

      <Modal
        title={<Space><SendOutlined style={{ color: token.colorPrimary }} /> {t('surveys.publishSurvey')}</Space>}
        open={publishModalOpen}
        onCancel={() => setPublishModalOpen(false)}
        onOk={handlePublish}
        confirmLoading={saving}
        okText={t('surveys.publish')}
      >
        <div style={{ display: 'flex', flexDirection: 'column', gap: 16, marginTop: 8 }}>
          <div>
            <Text strong style={{ display: 'block', marginBottom: 8 }}>{t('surveys.publishPublic')}</Text>
            <Switch
              checked={publishIsPublic}
              onChange={(v) => setPublishIsPublic(v)}
              checkedChildren={<GlobalOutlined />}
              unCheckedChildren={<LockOutlined />}
            />
            <Text type="secondary" style={{ display: 'block', fontSize: 12, marginTop: 4 }}>
              {publishIsPublic ? t('surveys.publishPublicDesc') : t('surveys.publishPrivateDesc')}
            </Text>
          </div>
          <div>
            <Text strong style={{ display: 'block', marginBottom: 8 }}>{t('surveys.targetClientTypes')}</Text>
            <Select
              mode="multiple"
              style={{ width: '100%' }}
              value={publishClientTypes}
              onChange={(v) => setPublishClientTypes(v)}
              options={CLIENT_TYPE_OPTIONS}
              placeholder={t('surveys.targetClientTypesPlaceholder')}
            />
            <Text type="secondary" style={{ display: 'block', fontSize: 12, marginTop: 4 }}>
              {t('surveys.targetClientTypesDesc')}
            </Text>
          </div>
        </div>
      </Modal>

      <Modal
        title={<Space><BarChartOutlined style={{ color: token.colorPrimary }} /> {t('surveys.responsesTitle')}</Space>}
        open={responsesModalOpen}
        onCancel={() => setResponsesModalOpen(false)}
        footer={<Button onClick={() => setResponsesModalOpen(false)}>{t('common.close')}</Button>}
        width={800}
      >
        {responsesLoading ? (
          <Spin style={{ display: 'block', margin: '32px auto' }} />
        ) : responses.length === 0 ? (
          <Empty description={t('surveys.noResponses')} image={Empty.PRESENTED_IMAGE_SIMPLE} />
        ) : (
          <Table
            dataSource={responses}
            rowKey="id"
            size="small"
            pagination={{ pageSize: 10 }}
            columns={[
              { title: '#', dataIndex: 'id', width: 50 },
              { title: t('surveys.respondent'), key: 'respondent', render: (_: any, r: SurveyResponse) => r.client_name || r.respondent_type || t('surveys.anonymous') },
              { title: t('surveys.respondentType'), dataIndex: 'respondent_type', width: 100, render: (v: string) => v ? <Tag>{v}</Tag> : '—' },
              { title: t('surveys.submittedAt'), dataIndex: 'submitted_at', width: 140, render: (v: string) => new Date(v).toLocaleString() },
              {
                title: t('surveys.answers'),
                dataIndex: 'answers',
                render: (answers: Record<string, unknown>) => (
                  <Popover
                    content={
                      <div style={{ maxWidth: 400 }}>
                        <pre style={{ fontSize: 11, margin: 0 }}>{JSON.stringify(answers, null, 2)}</pre>
                      </div>
                    }
                    title={t('surveys.answers')}
                  >
                    <Button size="small" icon={<EyeOutlined />}>{t('common.view')}</Button>
                  </Popover>
                ),
              },
            ]}
          />
        )}
      </Modal>
    </div>
  );
}

function findIndex(arr: SavedSurvey[], id: number): number {
  return arr.findIndex((s) => s.id === id);
}
