import { useEffect, useState, useCallback } from 'react';
import {
  Card, Row, Col, Input, Button, Space, Typography, Tag, Table, Spin,
  Popconfirm, Empty,
  Select, message, Tabs, theme,
} from 'antd';
import {
  FileTextOutlined, ThunderboltOutlined, EyeOutlined,
  CopyOutlined, CheckOutlined, ArrowLeftOutlined,
  DownloadOutlined, SaveOutlined, ShareAltOutlined,
  BookOutlined, DeleteOutlined, LinkOutlined,
  ExportOutlined, PlusOutlined, MinusCircleOutlined,
  EditOutlined,
} from '@ant-design/icons';
import api from '../lib/api';
import type { GeneratedSurvey, SurveyField, SavedSurvey } from '../lib/types';

const { Title, Text, Paragraph } = Typography;

function esc(s: string) {
  return s.replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;').replace(/"/g, '&quot;');
}

function buildFieldHtml(field: SurveyField, i: number): string {
  const req = field.required ? '<span style="color:#ef4444">*</span>' : '';
  const nm = `f_${i}`;
  const lbl = `<div class="field"><label for="${nm}">${esc(field.label)} ${req}</label>`;
  let inp = '';
  switch (field.type) {
    case 'textarea':
      inp = `<textarea id="${nm}" name="${nm}" placeholder="${esc(field.placeholder ?? '')}"${field.required ? ' required' : ''}></textarea>`;
      break;
    case 'select':
      inp = `<select id="${nm}" name="${nm}"${field.required ? ' required' : ''}><option value="">Select…</option>${(field.options ?? []).map((o) => `<option value="${esc(o)}">${esc(o)}</option>`).join('')}</select>`;
      break;
    case 'radio':
      inp = `<div class="opts">${(field.options ?? []).map((o) => `<label><input type="radio" name="${nm}" value="${esc(o)}"${field.required ? ' required' : ''}/> ${esc(o)}</label>`).join('')}</div>`;
      break;
    case 'checkbox':
      inp = `<div class="opts">${(field.options ?? []).map((o) => `<label><input type="checkbox" name="${nm}[]" value="${esc(o)}"/> ${esc(o)}</label>`).join('')}</div>`;
      break;
    case 'rating':
      inp = `<div class="stars">${Array.from({ length: field.max ?? 5 }, (_, k) => `<input type="radio" name="${nm}" id="${nm}_${k + 1}" value="${k + 1}"/><label for="${nm}_${k + 1}">★</label>`).join('')}</div>`;
      break;
    default:
      inp = `<input type="${esc(field.type)}" id="${nm}" name="${nm}" placeholder="${esc(field.placeholder ?? '')}"${field.required ? ' required' : ''}/>`;
  }
  return `${lbl}${inp}</div>`;
}

function generateHtml(survey: GeneratedSurvey): string {
  const fields = survey.fields.map(buildFieldHtml).join('\n');
  return `<!DOCTYPE html>
<html lang="en"><head>
<meta charset="UTF-8"/>
<meta name="viewport" content="width=device-width,initial-scale=1.0"/>
<title>${esc(survey.title)}</title>
<style>
*,*::before,*::after{box-sizing:border-box}
body{font-family:-apple-system,BlinkMacSystemFont,'Segoe UI',sans-serif;max-width:680px;margin:40px auto;padding:0 20px;color:#1e293b;background:#fff;line-height:1.6}
h1{font-size:1.5rem;font-weight:700;margin-bottom:6px}
p.d{color:#64748b;margin-bottom:32px;font-size:.95rem}
.field{margin-bottom:20px}
label{display:block;font-size:.875rem;font-weight:600;color:#374151;margin-bottom:6px}
input,textarea,select{width:100%;padding:8px 12px;border:1px solid #d1d5db;border-radius:6px;font-size:.9rem;color:#1e293b;background:#f9fafb}
input:focus,textarea:focus,select:focus{outline:none;border-color:#2563eb;background:#fff}
textarea{resize:vertical;min-height:80px}
.opts label{font-weight:400;display:flex;align-items:center;gap:8px;margin-bottom:4px}
.stars input[type=radio]{display:none}.stars label{font-size:1.5rem;cursor:pointer;color:#d1d5db;margin:0}
.btn{display:block;width:100%;padding:12px;background:#2563eb;color:#fff;border:none;border-radius:8px;font-size:1rem;font-weight:600;cursor:pointer;margin-top:32px}
.btn:hover{background:#1d4ed8}
footer{margin-top:48px;text-align:center;font-size:.75rem;color:#94a3b8}
@media print{body{margin:0}.btn{display:none}}
</style></head>
<body>
<h1>${esc(survey.title)}</h1>
${survey.description ? `<p class="d">${esc(survey.description)}</p>` : ''}
<form>
${fields}
<button type="submit" class="btn">Submit</button>
</form>
<footer>Generated by ISET Observatory · Survey Generator</footer>
</body></html>`;
}

const PLATFORMS = [
  { name: 'Google Forms', desc: 'Free, unlimited responses, Google account required.', color: '#4285f4', url: 'https://forms.google.com/create' },
  { name: 'Tally.so', desc: 'Free, unlimited responses, no sign-up required to fill.', color: '#2c2c2c', url: 'https://tally.so' },
  { name: 'Typeform', desc: 'Beautiful conversational forms, free tier available.', color: '#262627', url: 'https://www.typeform.com' },
  { name: 'Microsoft Forms', desc: 'Integrated with Microsoft 365, great for institutions.', color: '#0078d4', url: 'https://forms.microsoft.com' },
];

const FIELD_TYPES: { value: SurveyField['type']; label: string }[] = [
  { value: 'text', label: 'Text' },
  { value: 'textarea', label: 'Text Area' },
  { value: 'number', label: 'Number' },
  { value: 'email', label: 'Email' },
  { value: 'date', label: 'Date' },
  { value: 'select', label: 'Select' },
  { value: 'radio', label: 'Radio' },
  { value: 'checkbox', label: 'Checkbox' },
  { value: 'rating', label: 'Rating' },
];

function SurveyFieldPreview({ field }: { field: SurveyField }) {
  const { token } = theme.useToken();

  return (
    <div>
      <label style={{ display: 'block', fontSize: 14, fontWeight: 500, marginBottom: 6, color: token.colorTextSecondary }}>
        {field.label}
        {field.required && <Text type="danger"> *</Text>}
      </label>
      {(field.type === 'text' || field.type === 'email' || field.type === 'date') && (
        <Input type={field.type} placeholder={field.placeholder} disabled />
      )}
      {field.type === 'number' && (
        <Input type="number" placeholder={field.placeholder} disabled />
      )}
      {field.type === 'textarea' && (
        <Input.TextArea placeholder={field.placeholder} rows={3} disabled />
      )}
      {field.type === 'select' && (
        <Select disabled style={{ width: '100%' }} placeholder="Select…" options={field.options?.map((o) => ({ value: o, label: o }))} />
      )}
      {field.type === 'radio' && (
        <div style={{ display: 'flex', flexDirection: 'column', gap: 4 }}>
          {field.options?.map((o) => (
            <label key={o} style={{ display: 'flex', alignItems: 'center', gap: 8 }}>
              <input type="radio" disabled /> <Text type="secondary">{o}</Text>
            </label>
          ))}
        </div>
      )}
      {field.type === 'checkbox' && (
        <div style={{ display: 'flex', flexDirection: 'column', gap: 4 }}>
          {field.options?.map((o) => (
            <label key={o} style={{ display: 'flex', alignItems: 'center', gap: 8 }}>
              <input type="checkbox" disabled /> <Text type="secondary">{o}</Text>
            </label>
          ))}
        </div>
      )}
      {field.type === 'rating' && (
        <Space>
          {Array.from({ length: field.max || 5 }, (_, i) => (
            <span key={i} style={{ fontSize: 24, color: i < 3 ? token.colorWarning : token.colorBorder }}>★</span>
          ))}
        </Space>
      )}
    </div>
  );
}

export default function SurveyGeneratorPage() {
  const { token } = theme.useToken();
  const [goal, setGoal] = useState('');
  const [context, setContext] = useState('');
  const [generating, setGenerating] = useState(false);
  const [survey, setSurvey] = useState<GeneratedSurvey | null>(null);
  const [copied, setCopied] = useState(false);
  const [previewMode, setPreviewMode] = useState(false);

  const [saved, setSaved] = useState<SavedSurvey[]>([]);
  const [loadingSaved, setLoadingSaved] = useState(true);
  const [saving, setSaving] = useState(false);
  const [savedId, setSavedId] = useState<number | null>(null);

  const [shareOpen, setShareOpen] = useState(false);
  const [shareUrl, setShareUrl] = useState('');
  const [copiedEmbed, setCopiedEmbed] = useState(false);
  const [copiedLink, setCopiedLink] = useState(false);

  const [editingFields, setEditingFields] = useState(false);

  const fetchSaved = useCallback(async () => {
    setLoadingSaved(true);
    try {
      const { data } = await api.get<{ success: boolean; data: SavedSurvey[] }>('/surveys');
      if (data.success) setSaved(data.data);
    } catch { /* non-fatal */ }
    finally { setLoadingSaved(false); }
  }, []);

  useEffect(() => { fetchSaved(); }, [fetchSaved]);

  async function handleGenerate(e: React.FormEvent) {
    e.preventDefault();
    if (!goal.trim() || generating) return;
    setGenerating(true);
    setSurvey(null);
    setPreviewMode(false);
    setSavedId(null);
    setShareOpen(false);
    setEditingFields(false);
    try {
      const res = await api.post('/ai/survey/generate', {
        goal: goal.trim(),
        context: context.trim() || undefined,
      });
      setSurvey(res.data.data);
    } catch (err: unknown) {
      const msg = (err as { response?: { data?: { message?: string } } })?.response?.data?.message;
      message.error(msg || 'Survey generation failed.');
    } finally {
      setGenerating(false);
    }
  }

  async function handleSave() {
    if (!survey || saving) return;
    setSaving(true);
    try {
      const { data } = await api.post<{ success: boolean; data: SavedSurvey }>('/surveys', {
        title: survey.title,
        description: survey.description,
        goal: survey.goal,
        schema: survey,
      });
      setSavedId(data.data.id);
      message.success('Survey saved.');
      await fetchSaved();
    } catch {
      message.error('Failed to save survey.');
    } finally {
      setSaving(false);
    }
  }

  function handleDownloadHtml() {
    if (!survey) return;
    const html = generateHtml(survey);
    const blob = new Blob([html], { type: 'text/html' });
    const a = document.createElement('a');
    a.href = URL.createObjectURL(blob);
    a.download = `${survey.title.replace(/[^a-z0-9]/gi, '_').toLowerCase()}.html`;
    a.click();
    URL.revokeObjectURL(a.href);
    message.success('HTML downloaded.');
  }

  async function copyJSON() {
    if (!survey) return;
    await navigator.clipboard.writeText(JSON.stringify(survey, null, 2));
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
    message.success('JSON copied to clipboard.');
  }

  async function copyEmbed() {
    const url = shareUrl.trim() || 'YOUR_SURVEY_URL';
    const snippet = `<iframe src="${url}" width="100%" height="600" style="border:none; border-radius:8px;" title="${survey?.title ?? 'Survey'}"></iframe>`;
    await navigator.clipboard.writeText(snippet);
    setCopiedEmbed(true);
    setTimeout(() => setCopiedEmbed(false), 2000);
  }

  async function copyLink() {
    await navigator.clipboard.writeText(shareUrl.trim());
    setCopiedLink(true);
    setTimeout(() => setCopiedLink(false), 2000);
  }

  async function downloadQrPng() {
    const url = shareUrl.trim();
    if (!url) return;
    const apiUrl = `https://api.qrserver.com/v1/create-qr-code/?size=200x200&data=${encodeURIComponent(url)}`;
    const res = await fetch(apiUrl);
    const blob = await res.blob();
    const objUrl = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = objUrl;
    a.download = `${survey?.title?.replace(/[^a-z0-9]/gi, '_').toLowerCase() ?? 'survey'}_qr.png`;
    a.click();
    URL.revokeObjectURL(objUrl);
  }

  function loadSavedSurvey(s: SavedSurvey & { schema?: GeneratedSurvey }) {
    setGoal(s.goal ?? '');
    setSavedId(s.id);
    setPreviewMode(false);
    setShareOpen(false);
    setEditingFields(false);
    message.info(`"${s.title}" is already saved. Re-generate to get a fresh copy.`);
  }

  async function deleteSaved(id: number) {
    try {
      await api.delete(`/surveys/${id}`);
      setSaved((prev) => prev.filter((s) => s.id !== id));
      if (savedId === id) setSavedId(null);
      message.success('Survey deleted.');
    } catch {
      message.error('Failed to delete.');
    }
  }

  function addField() {
    if (!survey) return;
    const newField: SurveyField = {
      id: `f_${Date.now()}`,
      type: 'text',
      label: 'New Field',
      placeholder: '',
      required: false,
    };
    setSurvey({ ...survey, fields: [...survey.fields, newField] });
  }

  function removeField(fieldId: string) {
    if (!survey) return;
    setSurvey({ ...survey, fields: survey.fields.filter((f) => f.id !== fieldId) });
  }

  function updateField(fieldId: string, updates: Partial<SurveyField>) {
    if (!survey) return;
    setSurvey({
      ...survey,
      fields: survey.fields.map((f) => f.id === fieldId ? { ...f, ...updates } : f),
    });
  }

  function moveField(fieldId: string, direction: 'up' | 'down') {
    if (!survey) return;
    const idx = survey.fields.findIndex((f) => f.id === fieldId);
    if (idx < 0) return;
    if (direction === 'up' && idx === 0) return;
    if (direction === 'down' && idx === survey.fields.length - 1) return;
    const newFields = [...survey.fields];
    const swapIdx = direction === 'up' ? idx - 1 : idx + 1;
    [newFields[idx], newFields[swapIdx]] = [newFields[swapIdx], newFields[idx]];
    setSurvey({ ...survey, fields: newFields });
  }

  if (previewMode && survey) {
    return (
      <div style={{ maxWidth: 640, margin: '0 auto', display: 'flex', flexDirection: 'column', gap: 24 }}>
        <Button
          type="link"
          icon={<ArrowLeftOutlined />}
          onClick={() => setPreviewMode(false)}
        >
          Back to editor
        </Button>
        <Card>
          <Title level={4}>{survey.title}</Title>
          <Paragraph type="secondary">{survey.description}</Paragraph>
          <div style={{ display: 'flex', flexDirection: 'column', gap: 20 }}>
            {survey.fields.map((field) => <SurveyFieldPreview key={field.id} field={field} />)}
          </div>
          <Button type="primary" block disabled style={{ marginTop: 24, opacity: 0.5 }}>
            Submit (Preview Only)
          </Button>
        </Card>
      </div>
    );
  }

  const tabItems = [
    {
      key: 'generate',
      label: <span><ThunderboltOutlined /> Generate</span>,
      children: (
        <Row gutter={[24, 24]}>
          <Col xs={24} lg={14}>
            <Card>
              <div style={{ marginBottom: 16 }}>
                <Text strong style={{ display: 'block', marginBottom: 4, fontSize: 14 }}>
                  How to use
                </Text>
                <Text type="secondary" style={{ fontSize: 13 }}>
                  Describe your survey goal below and the AI will generate a complete survey form with
                  relevant fields. You can then edit, preview, download, or share the result.
                </Text>
              </div>
              <form onSubmit={handleGenerate} style={{ display: 'flex', flexDirection: 'column', gap: 16 }}>
                <div>
                  <Text strong style={{ display: 'block', marginBottom: 4 }}>
                    Survey Goal <Text type="danger">*</Text>
                  </Text>
                  <Input.TextArea
                    value={goal}
                    onChange={(e) => setGoal(e.target.value)}
                    rows={3}
                    placeholder='e.g. "Collect feedback from alumni about employment status and satisfaction with ISET education"'
                  />
                </div>
                <div>
                  <Text strong style={{ display: 'block', marginBottom: 4 }}>
                    Additional Context <Text type="secondary">(optional)</Text>
                  </Text>
                  <Input
                    value={context}
                    onChange={(e) => setContext(e.target.value)}
                    placeholder="e.g. Target audience: 2020-2024 graduates, bilingual French/Arabic"
                  />
                </div>
                <Button
                  type="primary"
                  htmlType="submit"
                  icon={<ThunderboltOutlined />}
                  loading={generating}
                  disabled={generating || !goal.trim()}
                  size="large"
                  block
                >
                  {generating ? 'Generating…' : 'Generate Survey'}
                </Button>
              </form>
            </Card>
          </Col>

          <Col xs={24} lg={10}>
            <Card
              title={<Space><BookOutlined style={{ color: token.colorPrimary }} /> Saved Surveys</Space>}
              styles={{ body: { padding: loadingSaved ? 24 : 0 } }}
            >
              {loadingSaved ? (
                <Spin style={{ display: 'block', margin: '16px auto' }} />
              ) : saved.length === 0 ? (
                <Empty description="No saved surveys yet." image={Empty.PRESENTED_IMAGE_SIMPLE} style={{ padding: 24 }} />
              ) : (
                <div style={{ maxHeight: 400, overflowY: 'auto' }}>
                  {saved.map((s) => (
                    <div
                      key={s.id}
                      style={{
                        padding: '10px 16px',
                        cursor: 'pointer',
                        backgroundColor: savedId === s.id ? token.colorPrimaryBg : 'transparent',
                        borderLeft: savedId === s.id ? `3px solid ${token.colorPrimary}` : '3px solid transparent',
                        transition: 'all 0.2s',
                      }}
                      onClick={() => loadSavedSurvey(s)}
                    >
                      <div style={{ display: 'flex', alignItems: 'center', gap: 8 }}>
                        <div style={{ flex: 1, minWidth: 0 }}>
                          <Text strong ellipsis style={{ display: 'block', fontSize: 13 }}>{s.title}</Text>
                          <Text type="secondary" style={{ fontSize: 11 }}>{s.goal?.slice(0, 50)}{s.goal && s.goal.length > 50 ? '…' : ''}</Text>
                          <br />
                          <Text type="secondary" style={{ fontSize: 10 }}>{new Date(s.created_at).toLocaleDateString()}</Text>
                        </div>
                        <Popconfirm title="Remove this saved survey?" onConfirm={() => deleteSaved(s.id)} okButtonProps={{ danger: true }}>
                          <Button type="text" size="small" danger icon={<DeleteOutlined />} onClick={(e) => e.stopPropagation()} />
                        </Popconfirm>
                      </div>
                    </div>
                  ))}
                </div>
              )}
            </Card>
          </Col>
        </Row>
      ),
    },
    ...(survey
      ? [
          {
            key: 'result',
            label: <span><FileTextOutlined /> Result</span>,
            children: (
              <div style={{ display: 'flex', flexDirection: 'column', gap: 16 }}>
                <Card>
                  <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'flex-start', flexWrap: 'wrap', gap: 12 }}>
                    <div>
                      <Title level={4} style={{ margin: 0 }}>{survey.title}</Title>
                      <Paragraph type="secondary" style={{ margin: '4px 0 0' }}>{survey.description}</Paragraph>
                      <Text type="secondary" style={{ fontSize: 12, marginTop: 8, display: 'block' }}>
                        {survey.fields.length} fields generated
                        {savedId && <Tag color="success" style={{ marginLeft: 8 }}>Saved</Tag>}
                      </Text>
                    </div>
                    <Space wrap>
                      <Button icon={<EyeOutlined />} onClick={() => setPreviewMode(true)}>Preview</Button>
                      <Button icon={copied ? <CheckOutlined /> : <CopyOutlined />} onClick={copyJSON}>
                        {copied ? 'Copied!' : 'Copy JSON'}
                      </Button>
                      <Button icon={<DownloadOutlined />} onClick={handleDownloadHtml}>Download HTML</Button>
                      <Button type="primary" icon={<SaveOutlined />} onClick={handleSave} loading={saving} disabled={!!savedId}>
                        {savedId ? 'Saved' : saving ? 'Saving…' : 'Save'}
                      </Button>
                      <Button icon={<ShareAltOutlined />} onClick={() => setShareOpen((v) => !v)}>Share</Button>
                    </Space>
                  </div>
                </Card>

                {shareOpen && (
                  <Card>
                    <Title level={5} style={{ display: 'flex', alignItems: 'center', gap: 8 }}>
                      <ShareAltOutlined style={{ color: token.colorPrimary }} /> Share & Embed
                    </Title>

                    <div style={{ marginBottom: 16 }}>
                      <Text strong style={{ display: 'block', marginBottom: 4, fontSize: 12 }}>
                        Paste your hosted survey URL to generate a QR code
                      </Text>
                      <Space.Compact style={{ width: '100%' }}>
                        <Input
                          prefix={<LinkOutlined />}
                          value={shareUrl}
                          onChange={(e) => setShareUrl(e.target.value)}
                          placeholder="https://your-domain.com/survey.html"
                        />
                        {shareUrl.trim() && (
                          <Button icon={copiedLink ? <CheckOutlined /> : <CopyOutlined />} onClick={copyLink}>
                            {copiedLink ? 'Copied!' : 'Copy link'}
                          </Button>
                        )}
                      </Space.Compact>
                      <Text type="secondary" style={{ fontSize: 11, marginTop: 4, display: 'block' }}>
                        First, export the HTML file, host it (e.g. GitHub Pages, Netlify), then paste the public URL here.
                      </Text>
                    </div>

                    <Row gutter={24}>
                      <Col style={{ display: 'flex', flexDirection: 'column', alignItems: 'center', gap: 8 }}>
                        <div style={{ borderRadius: 12, padding: 12, backgroundColor: '#fff', border: `1px solid ${token.colorBorder}`, opacity: shareUrl.trim() ? 1 : 0.2 }}>
                          <img
                            src={`https://api.qrserver.com/v1/create-qr-code/?size=200x200&data=${encodeURIComponent(shareUrl.trim() || 'https://example.com')}`}
                            alt="QR code"
                            width={200}
                            height={200}
                          />
                        </div>
                        {shareUrl.trim() ? (
                          <Button size="small" icon={<DownloadOutlined />} onClick={downloadQrPng}>Download QR PNG</Button>
                        ) : (
                          <Text type="secondary" style={{ fontSize: 12 }}>Enter URL to generate QR</Text>
                        )}
                      </Col>
                      <Col flex="auto" style={{ display: 'flex', flexDirection: 'column', gap: 8 }}>
                        <Text strong style={{ fontSize: 12 }}>Embed snippet — paste into your LMS or website:</Text>
                        <pre style={{
                          fontSize: 12, padding: 12, borderRadius: 8,
                          backgroundColor: token.colorBgContainer, overflowX: 'auto',
                          border: `1px solid ${token.colorBorder}`,
                        }}>
                          {`<iframe\n src="${shareUrl.trim() || 'YOUR_SURVEY_URL'}"\n width="100%" height="600"\n style="border:none; border-radius:8px;"\n title="${survey.title}"\n></iframe>`}
                        </pre>
                        <Button size="small" icon={copiedEmbed ? <CheckOutlined /> : <CopyOutlined />} onClick={copyEmbed}>
                          {copiedEmbed ? 'Copied!' : 'Copy snippet'}
                        </Button>
                      </Col>
                    </Row>
                  </Card>
                )}

                <Card
                  title={
                    <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center' }}>
                      <Space><EditOutlined style={{ color: token.colorPrimary }} /> Survey Fields</Space>
                      <Space>
                        <Button
                          size="small"
                          type={editingFields ? 'primary' : 'default'}
                          icon={<EditOutlined />}
                          onClick={() => setEditingFields((v) => !v)}
                        >
                          {editingFields ? 'Done Editing' : 'Edit Fields'}
                        </Button>
                        {editingFields && (
                          <Button size="small" icon={<PlusOutlined />} onClick={addField}>Add Field</Button>
                        )}
                      </Space>
                    </div>
                  }
                  size="small"
                >
                  {editingFields ? (
                    <div style={{ display: 'flex', flexDirection: 'column', gap: 8 }}>
                      {survey.fields.map((field, idx) => (
                        <Card
                          key={field.id}
                          size="small"
                          style={{ backgroundColor: token.colorBgContainer }}
                        >
                          <Row gutter={[12, 8]} align="middle">
                            <Col flex="none">
                              <Space direction="vertical" size={2}>
                                <Button
                                  type="text"
                                  size="small"
                                  icon={<span style={{ fontSize: 10 }}>▲</span>}
                                  disabled={idx === 0}
                                  onClick={() => moveField(field.id, 'up')}
                                />
                                <Button
                                  type="text"
                                  size="small"
                                  icon={<span style={{ fontSize: 10 }}>▼</span>}
                                  disabled={idx === survey.fields.length - 1}
                                  onClick={() => moveField(field.id, 'down')}
                                />
                              </Space>
                            </Col>
                            <Col xs={24} sm={8} md={6}>
                              <Text type="secondary" style={{ fontSize: 11, display: 'block', marginBottom: 2 }}>Label</Text>
                              <Input
                                size="small"
                                value={field.label}
                                onChange={(e) => updateField(field.id, { label: e.target.value })}
                              />
                            </Col>
                            <Col xs={12} sm={6} md={4}>
                              <Text type="secondary" style={{ fontSize: 11, display: 'block', marginBottom: 2 }}>Type</Text>
                              <Select
                                size="small"
                                style={{ width: '100%' }}
                                value={field.type}
                                onChange={(v) => updateField(field.id, { type: v as SurveyField['type'] })}
                                options={FIELD_TYPES}
                              />
                            </Col>
                            <Col xs={12} sm={6} md={4}>
                              <Text type="secondary" style={{ fontSize: 11, display: 'block', marginBottom: 2 }}>Placeholder</Text>
                              <Input
                                size="small"
                                value={field.placeholder ?? ''}
                                onChange={(e) => updateField(field.id, { placeholder: e.target.value })}
                              />
                            </Col>
                            <Col xs={12} sm={4} md={3}>
                              <Text type="secondary" style={{ fontSize: 11, display: 'block', marginBottom: 2 }}>Required</Text>
                              <Select
                                size="small"
                                style={{ width: '100%' }}
                                value={field.required ? 'yes' : 'no'}
                                onChange={(v) => updateField(field.id, { required: v === 'yes' })}
                                options={[{ value: 'yes', label: 'Yes' }, { value: 'no', label: 'No' }]}
                              />
                            </Col>
                            <Col xs={24} sm={12} md={5}>
                              <Text type="secondary" style={{ fontSize: 11, display: 'block', marginBottom: 2 }}>
                                Options <Text type="secondary">(comma-sep)</Text>
                              </Text>
                              <Input
                                size="small"
                                value={(field.options ?? []).join(', ')}
                                onChange={(e) => {
                                  const opts = e.target.value.split(',').map((o) => o.trim()).filter(Boolean);
                                  updateField(field.id, { options: opts.length ? opts : undefined });
                                }}
                                disabled={!['select', 'radio', 'checkbox'].includes(field.type)}
                              />
                            </Col>
                            <Col flex="none">
                              <Button
                                type="text"
                                danger
                                size="small"
                                icon={<MinusCircleOutlined />}
                                onClick={() => removeField(field.id)}
                                style={{ marginTop: 18 }}
                              />
                            </Col>
                          </Row>
                        </Card>
                      ))}
                    </div>
                  ) : (
                    <Table
                      dataSource={survey.fields.map((f, i) => ({ key: f.id, ...f, idx: i }))}
                      pagination={false}
                      size="small"
                      columns={[
                        { title: '#', dataIndex: 'idx', width: 40, render: (i: number) => i + 1 },
                        { title: 'Label', dataIndex: 'label', ellipsis: true },
                        { title: 'Type', dataIndex: 'type', width: 100, render: (v: string) => <Tag>{v}</Tag> },
                        { title: 'Required', dataIndex: 'required', width: 80, render: (v: boolean) => v ? <Tag color="red">Yes</Tag> : <Tag>No</Tag> },
                        { title: 'Options', dataIndex: 'options', render: (v: string[] | undefined) => v?.join(', ') || '—' },
                      ]}
                    />
                  )}
                </Card>

                <Card title={<Space><ExportOutlined style={{ color: token.colorPrimary }} /> Publish on a free platform</Space>}>
                  <Paragraph type="secondary" style={{ fontSize: 12 }}>
                    Copy your questions into one of these free survey platforms for easy response collection.
                  </Paragraph>
                  <Row gutter={[12, 12]}>
                    {PLATFORMS.map((p) => (
                      <Col xs={12} md={6} key={p.name}>
                        <a href={p.url} target="_blank" rel="noopener noreferrer" style={{ textDecoration: 'none' }}>
                          <Card hoverable size="small" style={{ textAlign: 'center' }}>
                            <Space direction="vertical" size={4}>
                              <Text strong style={{ color: p.color }}>{p.name}</Text>
                              <Text type="secondary" style={{ fontSize: 11 }}>{p.desc}</Text>
                            </Space>
                          </Card>
                        </a>
                      </Col>
                    ))}
                  </Row>
                </Card>

                <Card title="JSON Schema" size="small">
                  <pre style={{
                    padding: 16, fontSize: 12, overflowX: 'auto', maxHeight: 256,
                    backgroundColor: token.colorBgContainer, color: token.colorSuccess,
                    borderRadius: 8,
                  }}>
                    {JSON.stringify(survey, null, 2)}
                  </pre>
                </Card>
              </div>
            ),
          },
        ]
      : []),
  ];

  return (
    <div style={{ display: 'flex', flexDirection: 'column', gap: 20 }}>
      <div>
        <Title level={3} style={{ display: 'flex', alignItems: 'center', gap: 8, margin: 0 }}>
          <FileTextOutlined style={{ color: token.colorPrimary }} /> AI Survey Generator
        </Title>
        <Text type="secondary">Describe your survey goal and AI will generate a professional survey form.</Text>
      </div>

      <Tabs items={tabItems} defaultActiveKey="generate" />
    </div>
  );
}
