import { useEffect, useState, useCallback } from 'react';
import {
  ClipboardList, Wand2, Loader2, Eye, Copy, Check, ArrowLeft, Star,
  Download, Save, Share2, ChevronDown, ChevronUp, Link,
  ExternalLink, BookMarked, Trash2,
} from 'lucide-react';
import api from '../lib/api';
import type { GeneratedSurvey, SurveyField, SavedSurvey } from '../lib/types';

// ─── helpers ────────────────────────────────────────────────────────────────

function esc(s: string) {
  return s.replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;').replace(/"/g, '&quot;');
}

function buildFieldHtml(field: SurveyField, i: number): string {
  const req = field.required ? '<span style="color:#ef4444">*</span>' : '';
  const nm = `f_${i}`;
  const lbl = `<div class="field"><label for="${nm}">${esc(field.label)} ${req}</label>`;
  let inp = '';
  switch (field.type) {
    case 'textarea':
      inp = `<textarea id="${nm}" name="${nm}" placeholder="${esc(field.placeholder ?? '')}"${field.required ? ' required' : ''}></textarea>`;
      break;
    case 'select':
      inp = `<select id="${nm}" name="${nm}"${field.required ? ' required' : ''}><option value="">Select…</option>${(field.options ?? []).map((o) => `<option value="${esc(o)}">${esc(o)}</option>`).join('')}</select>`;
      break;
    case 'radio':
      inp = `<div class="opts">${(field.options ?? []).map((o) => `<label><input type="radio" name="${nm}" value="${esc(o)}"${field.required ? ' required' : ''}/> ${esc(o)}</label>`).join('')}</div>`;
      break;
    case 'checkbox':
      inp = `<div class="opts">${(field.options ?? []).map((o) => `<label><input type="checkbox" name="${nm}[]" value="${esc(o)}"/> ${esc(o)}</label>`).join('')}</div>`;
      break;
    case 'rating':
      inp = `<div class="stars">${Array.from({ length: field.max ?? 5 }, (_, k) => `<input type="radio" name="${nm}" id="${nm}_${k + 1}" value="${k + 1}"/><label for="${nm}_${k + 1}">★</label>`).join('')}</div>`;
      break;
    default:
      inp = `<input type="${esc(field.type)}" id="${nm}" name="${nm}" placeholder="${esc(field.placeholder ?? '')}"${field.required ? ' required' : ''}/>`;
  }
  return `${lbl}${inp}</div>`;
}

function generateHtml(survey: GeneratedSurvey): string {
  const fields = survey.fields.map(buildFieldHtml).join('\n');
  return `<!DOCTYPE html>
<html lang="en"><head>
<meta charset="UTF-8"/>
<meta name="viewport" content="width=device-width,initial-scale=1.0"/>
<title>${esc(survey.title)}</title>
<style>
*,*::before,*::after{box-sizing:border-box}
body{font-family:-apple-system,BlinkMacSystemFont,'Segoe UI',sans-serif;max-width:680px;margin:40px auto;padding:0 20px;color:#1e293b;background:#fff;line-height:1.6}
h1{font-size:1.5rem;font-weight:700;margin-bottom:6px}
p.d{color:#64748b;margin-bottom:32px;font-size:.95rem}
.field{margin-bottom:20px}
label{display:block;font-size:.875rem;font-weight:600;color:#374151;margin-bottom:6px}
input,textarea,select{width:100%;padding:8px 12px;border:1px solid #d1d5db;border-radius:6px;font-size:.9rem;color:#1e293b;background:#f9fafb}
input:focus,textarea:focus,select:focus{outline:none;border-color:#2563eb;background:#fff}
textarea{resize:vertical;min-height:80px}
.opts label{font-weight:400;display:flex;align-items:center;gap:8px;margin-bottom:4px}
.stars input[type=radio]{display:none}.stars label{font-size:1.5rem;cursor:pointer;color:#d1d5db;margin:0}
.btn{display:block;width:100%;padding:12px;background:#2563eb;color:#fff;border:none;border-radius:8px;font-size:1rem;font-weight:600;cursor:pointer;margin-top:32px}
.btn:hover{background:#1d4ed8}
footer{margin-top:48px;text-align:center;font-size:.75rem;color:#94a3b8}
@media print{body{margin:0}.btn{display:none}}
</style></head>
<body>
<h1>${esc(survey.title)}</h1>
${survey.description ? `<p class="d">${esc(survey.description)}</p>` : ''}
<form>
${fields}
<button type="submit" class="btn">Submit</button>
</form>
<footer>Generated by ISET Observatory · Survey Generator</footer>
</body></html>`;
}

const PLATFORMS = [
  {
    name: 'Google Forms',
    desc: 'Free, unlimited responses, Google account required.',
    color: '#4285f4',
    url: 'https://forms.google.com/create',
    emoji: '🇬',
  },
  {
    name: 'Tally.so',
    desc: 'Free, unlimited responses, no sign-up required to fill.',
    color: '#2c2c2c',
    url: 'https://tally.so',
    emoji: '📋',
  },
  {
    name: 'Typeform',
    desc: 'Beautiful conversational forms, free tier available.',
    color: '#262627',
    url: 'https://www.typeform.com',
    emoji: '✨',
  },
  {
    name: 'Microsoft Forms',
    desc: 'Integrated with Microsoft 365, great for institutions.',
    color: '#0078d4',
    url: 'https://forms.microsoft.com',
    emoji: '🏢',
  },
];

// ─── page component ─────────────────────────────────────────────────────────

export default function SurveyGeneratorPage() {
  const [goal, setGoal] = useState('');
  const [context, setContext] = useState('');
  const [generating, setGenerating] = useState(false);
  const [survey, setSurvey] = useState<GeneratedSurvey | null>(null);
  const [copied, setCopied] = useState(false);
  const [previewMode, setPreviewMode] = useState(false);

  // saved surveys sidebar
  const [saved, setSaved] = useState<SavedSurvey[]>([]);
  const [loadingSaved, setLoadingSaved] = useState(true);
  const [saving, setSaving] = useState(false);
  const [savedId, setSavedId] = useState<number | null>(null);

  // share panel
  const [shareOpen, setShareOpen] = useState(false);
  const [shareUrl, setShareUrl] = useState('');
  const [copiedEmbed, setCopiedEmbed] = useState(false);
  const [copiedLink, setCopiedLink] = useState(false);
  // ── fetch saved surveys ──────────────────────────────────────────────────
  const fetchSaved = useCallback(async () => {
    setLoadingSaved(true);
    try {
      const { data } = await api.get<{ success: boolean; data: SavedSurvey[] }>('/surveys');
      if (data.success) setSaved(data.data);
    } catch { /* non-fatal */ }
    finally { setLoadingSaved(false); }
  }, []);

  useEffect(() => { fetchSaved(); }, [fetchSaved]);

  // ── actions ──────────────────────────────────────────────────────────────
  async function handleGenerate(e: React.FormEvent) {
    e.preventDefault();
    if (!goal.trim() || generating) return;
    setGenerating(true);
    setSurvey(null);
    setPreviewMode(false);
    setSavedId(null);
    setShareOpen(false);
    try {
      const res = await api.post('/ai/survey/generate', {
        goal: goal.trim(),
        context: context.trim() || undefined,
      });
      setSurvey(res.data.data);
    } catch (err: unknown) {
      const msg = (err as { response?: { data?: { message?: string } } })?.response?.data?.message;
      alert(msg || 'Survey generation failed.');
    } finally {
      setGenerating(false);
    }
  }

  async function handleSave() {
    if (!survey || saving) return;
    setSaving(true);
    try {
      const { data } = await api.post<{ success: boolean; data: SavedSurvey }>('/surveys', {
        title: survey.title,
        description: survey.description,
        goal: survey.goal,
        schema: survey,
      });
      setSavedId(data.data.id);
      await fetchSaved();
    } catch {
      alert('Failed to save survey.');
    } finally {
      setSaving(false);
    }
  }

  function handleDownloadHtml() {
    if (!survey) return;
    const html = generateHtml(survey);
    const blob = new Blob([html], { type: 'text/html' });
    const a = document.createElement('a');
    a.href = URL.createObjectURL(blob);
    a.download = `${survey.title.replace(/[^a-z0-9]/gi, '_').toLowerCase()}.html`;
    a.click();
    URL.revokeObjectURL(a.href);
  }

  async function copyJSON() {
    if (!survey) return;
    await navigator.clipboard.writeText(JSON.stringify(survey, null, 2));
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  }

  async function copyEmbed() {
    const url = shareUrl.trim() || 'YOUR_SURVEY_URL';
    const snippet = `<iframe src="${url}" width="100%" height="600" style="border:none; border-radius:8px;" title="${survey?.title ?? 'Survey'}"></iframe>`;
    await navigator.clipboard.writeText(snippet);
    setCopiedEmbed(true);
    setTimeout(() => setCopiedEmbed(false), 2000);
  }

  async function copyLink() {
    await navigator.clipboard.writeText(shareUrl.trim());
    setCopiedLink(true);
    setTimeout(() => setCopiedLink(false), 2000);
  }

  async function downloadQrPng() {
    const url = shareUrl.trim();
    if (!url) return;
    const apiUrl = `https://api.qrserver.com/v1/create-qr-code/?size=200x200&data=${encodeURIComponent(url)}`;
    const res = await fetch(apiUrl);
    const blob = await res.blob();
    const objUrl = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = objUrl;
    a.download = `${survey?.title?.replace(/[^a-z0-9]/gi, '_').toLowerCase() ?? 'survey'}_qr.png`;
    a.click();
    URL.revokeObjectURL(objUrl);
  }

  function loadSavedSurvey(s: SavedSurvey & { schema?: GeneratedSurvey }) {
    // schema stored as GeneratedSurvey inside the saved row - load from backend metadata
    setGoal(s.goal ?? '');
    setSavedId(s.id);
    setPreviewMode(false);
    setShareOpen(false);
    // We only have metadata from the list endpoint; for the full schema we'd need GET /api/surveys/:id
    // For now, show a toast indicating it's already saved
    alert(`"${s.title}" is already saved. Re-generate to get a fresh copy.`);
  }

  async function deleteSaved(id: number) {
    if (!confirm('Remove this saved survey?')) return;
    try {
      await api.delete(`/surveys/${id}`);
      setSaved((prev) => prev.filter((s) => s.id !== id));
      if (savedId === id) setSavedId(null);
    } catch {
      alert('Failed to delete.');
    }
  }

  // ─── preview mode ────────────────────────────────────────────────────────
  if (previewMode && survey) {
    return (
      <div className="max-w-2xl mx-auto space-y-6">
        <button
          onClick={() => setPreviewMode(false)}
          className="flex items-center gap-1.5 text-sm transition-colors"
          style={{ color: 'var(--ag-text2)' }}
          onMouseOver={(e) => (e.currentTarget.style.color = 'var(--ag-text)')}
          onMouseOut={(e) => (e.currentTarget.style.color = 'var(--ag-text2)')}
        >
          <ArrowLeft className="w-4 h-4" /> Back to editor
        </button>
        <div className="ag-card p-6 space-y-6">
          <div>
            <h2 className="text-xl font-bold" style={{ color: 'var(--ag-text)' }}>{survey.title}</h2>
            <p className="text-sm mt-1" style={{ color: 'var(--ag-text2)' }}>{survey.description}</p>
          </div>
          <div className="space-y-5">
            {survey.fields.map((field) => <SurveyFieldPreview key={field.id} field={field} />)}
          </div>
          <button
            type="button"
            className="w-full px-4 py-2.5 text-sm font-medium rounded-lg opacity-50 cursor-not-allowed text-white"
            style={{ background: 'var(--ag-accent)' }}
          >
            Submit (Preview Only)
          </button>
        </div>
      </div>
    );
  }

  // ─── main view ───────────────────────────────────────────────────────────
  return (
    <div className="flex gap-5 items-start">
      {/* ── Saved surveys sidebar ── */}
      <aside
        className="hidden lg:flex flex-col w-60 shrink-0 rounded-xl overflow-hidden"
        style={{ background: 'var(--ag-card)', border: '1px solid var(--ag-border)' }}
      >
        <div
          className="px-4 py-3 flex items-center gap-2"
          style={{ borderBottom: '1px solid var(--ag-border)' }}
        >
          <BookMarked className="w-4 h-4" style={{ color: 'var(--ag-accent)' }} />
          <span className="text-sm font-semibold" style={{ color: 'var(--ag-text)' }}>Saved Surveys</span>
        </div>
        <div className="flex-1 overflow-y-auto p-2 space-y-1 min-h-[120px]">
          {loadingSaved ? (
            <p className="text-xs px-2 py-3" style={{ color: 'var(--ag-text3)' }}>Loading…</p>
          ) : saved.length === 0 ? (
            <p className="text-xs px-2 py-3" style={{ color: 'var(--ag-text3)' }}>No saved surveys yet.</p>
          ) : (
            saved.map((s) => (
              <div
                key={s.id}
                className="flex items-start gap-2 px-2 py-2 rounded-lg cursor-pointer group"
                style={{
                  background: savedId === s.id ? 'var(--ag-accent)15' : 'transparent',
                  border: savedId === s.id ? '1px solid var(--ag-accent)33' : '1px solid transparent',
                }}
                onClick={() => loadSavedSurvey(s)}
              >
                <div className="flex-1 min-w-0">
                  <p className="text-xs font-medium truncate" style={{ color: 'var(--ag-text)' }}>{s.title}</p>
                  <p className="text-[10px] mt-0.5" style={{ color: 'var(--ag-text3)' }}>
                    {new Date(s.created_at).toLocaleDateString()}
                  </p>
                </div>
                <button
                  onClick={(e) => { e.stopPropagation(); deleteSaved(s.id); }}
                  className="opacity-0 group-hover:opacity-100 transition-opacity p-0.5 rounded"
                  style={{ color: 'var(--ag-text3)' }}
                >
                  <Trash2 className="w-3 h-3" />
                </button>
              </div>
            ))
          )}
        </div>
      </aside>

      {/* ── Main content ── */}
      <div className="flex-1 min-w-0 space-y-5">
        {/* Header */}
        <div>
          <h1 className="text-2xl font-bold flex items-center gap-2" style={{ color: 'var(--ag-text)' }}>
            <ClipboardList className="w-6 h-6" style={{ color: 'var(--ag-accent)' }} />
            AI Survey Generator
          </h1>
          <p className="text-sm mt-1" style={{ color: 'var(--ag-text2)' }}>
            Describe your survey goal and AI will generate a professional survey form.
          </p>
        </div>

        {/* Generation form */}
        <form onSubmit={handleGenerate} className="ag-card p-5 space-y-4">
          <div>
            <label className="block text-sm font-medium mb-1.5" style={{ color: 'var(--ag-text2)' }}>
              Survey Goal <span style={{ color: 'var(--ag-red)' }}>*</span>
            </label>
            <textarea
              value={goal}
              onChange={(e) => setGoal(e.target.value)}
              rows={3}
              placeholder='e.g. "Collect feedback from alumni about employment status and satisfaction with ISET education"'
              className="ag-input w-full px-3 py-2 text-sm resize-none"
            />
          </div>
          <div>
            <label className="block text-sm font-medium mb-1.5" style={{ color: 'var(--ag-text2)' }}>
              Additional Context <span style={{ color: 'var(--ag-text3)' }}>(optional)</span>
            </label>
            <input
              type="text"
              value={context}
              onChange={(e) => setContext(e.target.value)}
              placeholder="e.g. Target audience: 2020-2024 graduates, bilingual French/Arabic"
              className="ag-input w-full px-3 py-2.5 text-sm"
            />
          </div>
          <button
            type="submit"
            disabled={generating || !goal.trim()}
            className="ag-btn-primary flex items-center gap-2 px-5 py-2.5 text-sm"
          >
            {generating
              ? <><Loader2 className="w-4 h-4 animate-spin" /> Generating…</>
              : <><Wand2 className="w-4 h-4" /> Generate Survey</>}
          </button>
        </form>

        {/* ── Survey result ── */}
        {survey && (
          <div className="space-y-4">
            {/* Survey header card */}
            <div className="ag-card p-5">
              <div className="flex items-start justify-between gap-4 flex-wrap">
                <div>
                  <h2 className="text-lg font-bold" style={{ color: 'var(--ag-text)' }}>{survey.title}</h2>
                  <p className="text-sm mt-1" style={{ color: 'var(--ag-text2)' }}>{survey.description}</p>
                  <p className="text-xs mt-2" style={{ color: 'var(--ag-text3)' }}>
                    {survey.fields.length} fields generated
                    {savedId && <span className="ml-2 text-green-500">· Saved ✓</span>}
                  </p>
                </div>
                <div className="flex flex-wrap gap-2 shrink-0">
                  <button
                    onClick={() => setPreviewMode(true)}
                    className="ag-btn-ghost flex items-center gap-1.5 px-3 py-2 text-xs"
                  >
                    <Eye className="w-3.5 h-3.5" /> Preview
                  </button>
                  <button
                    onClick={copyJSON}
                    className="ag-btn-ghost flex items-center gap-1.5 px-3 py-2 text-xs"
                  >
                    {copied
                      ? <><Check className="w-3.5 h-3.5" style={{ color: 'var(--ag-green)' }} /> Copied!</>
                      : <><Copy className="w-3.5 h-3.5" /> Copy JSON</>}
                  </button>
                  <button
                    onClick={handleDownloadHtml}
                    className="ag-btn-ghost flex items-center gap-1.5 px-3 py-2 text-xs"
                  >
                    <Download className="w-3.5 h-3.5" /> Download HTML
                  </button>
                  <button
                    onClick={handleSave}
                    disabled={saving || !!savedId}
                    className="ag-btn-primary flex items-center gap-1.5 px-3 py-2 text-xs disabled:opacity-50"
                  >
                    {saving
                      ? <Loader2 className="w-3.5 h-3.5 animate-spin" />
                      : <Save className="w-3.5 h-3.5" />}
                    {savedId ? 'Saved' : saving ? 'Saving…' : 'Save'}
                  </button>
                  <button
                    onClick={() => setShareOpen((v) => !v)}
                    className="ag-btn-ghost flex items-center gap-1.5 px-3 py-2 text-xs"
                  >
                    <Share2 className="w-3.5 h-3.5" />
                    Share
                    {shareOpen ? <ChevronUp className="w-3 h-3" /> : <ChevronDown className="w-3 h-3" />}
                  </button>
                </div>
              </div>
            </div>

            {/* ── Share / Embed panel (Issue 14 + 16) ── */}
            {shareOpen && (
              <div className="ag-card p-5 space-y-5">
                <h3 className="text-sm font-semibold flex items-center gap-2" style={{ color: 'var(--ag-text)' }}>
                  <Share2 className="w-4 h-4" style={{ color: 'var(--ag-accent)' }} />
                  Share &amp; Embed
                </h3>

                {/* URL input for QR */}
                <div>
                  <label className="block text-xs font-medium mb-1.5" style={{ color: 'var(--ag-text2)' }}>
                    Paste your hosted survey URL to generate a QR code
                  </label>
                  <div className="flex gap-2">
                    <div className="relative flex-1">
                      <Link className="absolute left-3 top-1/2 -translate-y-1/2 w-3.5 h-3.5" style={{ color: 'var(--ag-text3)' }} />
                      <input
                        type="url"
                        value={shareUrl}
                        onChange={(e) => setShareUrl(e.target.value)}
                        placeholder="https://your-domain.com/survey.html"
                        className="ag-input w-full pl-9 pr-3 py-2 text-sm"
                      />
                    </div>
                    {shareUrl.trim() && (
                      <button onClick={copyLink} className="ag-btn-ghost flex items-center gap-1.5 px-3 py-2 text-xs shrink-0">
                        {copiedLink ? <Check className="w-3.5 h-3.5" style={{ color: 'var(--ag-green)' }} /> : <Copy className="w-3.5 h-3.5" />}
                        Copy link
                      </button>
                    )}
                  </div>
                  <p className="text-xs mt-1.5" style={{ color: 'var(--ag-text3)' }}>
                    First, export the HTML file below, host it somewhere (e.g. GitHub Pages, Netlify), then paste the public URL here.
                  </p>
                </div>

                {/* QR + embed snippet */}
                <div className="flex flex-col sm:flex-row gap-5">
                  {/* QR code */}
                  <div className="flex flex-col items-center gap-3">
                    <div
                      className="rounded-xl p-3"
                      style={{ background: '#fff', border: '1px solid var(--ag-border)', opacity: shareUrl.trim() ? 1 : 0.2 }}
                    >
                      <img
                        src={`https://api.qrserver.com/v1/create-qr-code/?size=200x200&data=${encodeURIComponent(shareUrl.trim() || 'https://example.com')}`}
                        alt="QR code"
                        width={200}
                        height={200}
                        className="block"
                      />
                    </div>
                    {shareUrl.trim() && (
                      <button
                        onClick={downloadQrPng}
                        className="ag-btn-ghost flex items-center gap-1.5 px-3 py-2 text-xs"
                      >
                        <Download className="w-3.5 h-3.5" /> Download QR PNG
                      </button>
                    )}
                    {!shareUrl.trim() && (
                      <p className="text-xs" style={{ color: 'var(--ag-text3)' }}>Enter URL to generate QR</p>
                    )}
                  </div>

                  {/* Embed snippet */}
                  <div className="flex-1 space-y-2">
                    <p className="text-xs font-medium" style={{ color: 'var(--ag-text2)' }}>
                      Embed snippet — paste into your LMS or website:
                    </p>
                    <pre
                      className="text-xs p-3 rounded-lg overflow-x-auto leading-relaxed"
                      style={{ background: 'var(--ag-sidebar)', color: '#7dd3fc', border: '1px solid var(--ag-border)' }}
                    >
{`<iframe
  src="${shareUrl.trim() || 'YOUR_SURVEY_URL'}"
  width="100%" height="600"
  style="border:none; border-radius:8px;"
  title="${survey.title}"
></iframe>`}
                    </pre>
                    <button
                      onClick={copyEmbed}
                      className="ag-btn-ghost flex items-center gap-1.5 px-3 py-2 text-xs"
                    >
                      {copiedEmbed
                        ? <><Check className="w-3.5 h-3.5" style={{ color: 'var(--ag-green)' }} /> Copied!</>
                        : <><Copy className="w-3.5 h-3.5" /> Copy snippet</>}
                    </button>
                  </div>
                </div>
              </div>
            )}

            {/* ── Platform suggestions (Issue 15) ── */}
            <div className="ag-card p-5">
              <h3 className="text-sm font-semibold mb-3 flex items-center gap-2" style={{ color: 'var(--ag-text)' }}>
                <ExternalLink className="w-4 h-4" style={{ color: 'var(--ag-accent)' }} />
                Publish on a free platform
              </h3>
              <p className="text-xs mb-4" style={{ color: 'var(--ag-text2)' }}>
                Copy your questions into one of these free survey platforms for easy response collection.
              </p>
              <div className="grid sm:grid-cols-2 gap-3">
                {PLATFORMS.map((p) => (
                  <a
                    key={p.name}
                    href={p.url}
                    target="_blank"
                    rel="noopener noreferrer"
                    className="flex items-start gap-3 p-3 rounded-xl transition hover:-translate-y-0.5"
                    style={{ background: 'var(--ag-bg)', border: '1px solid var(--ag-border)', textDecoration: 'none' }}
                  >
                    <span className="text-xl shrink-0 mt-0.5">{p.emoji}</span>
                    <div className="min-w-0">
                      <p className="text-xs font-semibold" style={{ color: p.color }}>{p.name}</p>
                      <p className="text-[11px] mt-0.5 leading-snug" style={{ color: 'var(--ag-text3)' }}>{p.desc}</p>
                    </div>
                    <ExternalLink className="w-3 h-3 shrink-0 mt-0.5 ml-auto" style={{ color: 'var(--ag-text3)' }} />
                  </a>
                ))}
              </div>
            </div>

            {/* Fields table */}
            <div className="ag-card overflow-hidden">
              <div className="px-5 py-3 ag-table-head">
                <h3 className="text-sm font-medium">Survey Fields</h3>
              </div>
              <table className="w-full text-sm">
                <thead>
                  <tr className="ag-table-head">
                    <th className="px-5 py-2.5 text-left">#</th>
                    <th className="px-5 py-2.5 text-left">Label</th>
                    <th className="px-5 py-2.5 text-left">Type</th>
                    <th className="px-5 py-2.5 text-left">Required</th>
                    <th className="px-5 py-2.5 text-left">Options</th>
                  </tr>
                </thead>
                <tbody>
                  {survey.fields.map((f, i) => (
                    <tr key={f.id} className="ag-table-row">
                      <td className="px-5 py-2.5" style={{ color: 'var(--ag-text3)' }}>{i + 1}</td>
                      <td className="px-5 py-2.5" style={{ color: 'var(--ag-text)' }}>{f.label}</td>
                      <td className="px-5 py-2.5"><span className="ag-badge">{f.type}</span></td>
                      <td className="px-5 py-2.5" style={{ color: 'var(--ag-text2)' }}>{f.required ? 'Yes' : 'No'}</td>
                      <td className="px-5 py-2.5 max-w-[200px] truncate" style={{ color: 'var(--ag-text3)', fontSize: '0.7rem' }}>
                        {f.options?.join(', ') || '—'}
                      </td>
                    </tr>
                  ))}
                </tbody>
              </table>
            </div>

            {/* JSON schema */}
            <div className="ag-card overflow-hidden">
              <div className="px-5 py-3 ag-table-head">
                <h3 className="text-sm font-medium">JSON Schema</h3>
              </div>
              <pre className="p-4 text-xs overflow-x-auto max-h-64 font-mono" style={{ color: 'var(--ag-green)' }}>
                {JSON.stringify(survey, null, 2)}
              </pre>
            </div>
          </div>
        )}
      </div>
    </div>
  );
}

// ─── field preview component ─────────────────────────────────────────────────

function SurveyFieldPreview({ field }: { field: SurveyField }) {
  const labelStyle = { color: 'var(--ag-text2)' };
  const inputClass = 'ag-input w-full px-3 py-2 text-sm';

  return (
    <div>
      <label className="block text-sm font-medium mb-1.5" style={labelStyle}>
        {field.label}
        {field.required && <span className="ml-0.5" style={{ color: 'var(--ag-red)' }}>*</span>}
      </label>
      {(field.type === 'text' || field.type === 'email' || field.type === 'date') && (
        <input type={field.type} placeholder={field.placeholder} className={inputClass} disabled />
      )}
      {field.type === 'number' && (
        <input type="number" placeholder={field.placeholder} min={field.min} max={field.max} className={inputClass} disabled />
      )}
      {field.type === 'textarea' && (
        <textarea placeholder={field.placeholder} rows={3} className={`${inputClass} resize-none`} disabled />
      )}
      {field.type === 'select' && (
        <select className={inputClass} disabled>
          <option>Select…</option>
          {field.options?.map((o) => <option key={o}>{o}</option>)}
        </select>
      )}
      {field.type === 'radio' && (
        <div className="space-y-1.5">
          {field.options?.map((o) => (
            <label key={o} className="flex items-center gap-2 text-sm" style={{ color: 'var(--ag-text2)' }}>
              <input type="radio" name={field.id} disabled style={{ accentColor: 'var(--ag-accent)' }} /> {o}
            </label>
          ))}
        </div>
      )}
      {field.type === 'checkbox' && (
        <div className="space-y-1.5">
          {field.options?.map((o) => (
            <label key={o} className="flex items-center gap-2 text-sm" style={{ color: 'var(--ag-text2)' }}>
              <input type="checkbox" disabled style={{ accentColor: 'var(--ag-accent)' }} className="rounded" /> {o}
            </label>
          ))}
        </div>
      )}
      {field.type === 'rating' && (
        <div className="flex gap-1">
          {Array.from({ length: field.max || 5 }, (_, i) => (
            <Star key={i} className={`w-6 h-6 ${i < 3 ? 'fill-current' : ''}`}
              style={{ color: i < 3 ? 'var(--ag-amber)' : 'var(--ag-border)' }} />
          ))}
        </div>
      )}
    </div>
  );
}